const app=document.querySelector('#app'),notice=document.querySelector('#notice');let state,busy=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>'₹'+Number(x||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`;
const area=(name,label,value='')=>`<label>${label}<textarea name="${name}" required>${esc(value)}</textarea></label>`;
const check=(name,label,checked=false)=>`<label class="check"><input type="checkbox" name="${name}" ${checked?'checked':''}>${label}</label>`;
const submit=label=>`<button class="primary" type="submit">${label}</button>`;
const services=()=>state.services.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.te)}</option>`).join('');
async function refresh(){const r=await fetch('/api/state');const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load account');state=data;render();}
function render(){const {user,settings:s}=state;document.querySelector('#account').innerHTML=user?`${esc(user.email)}<small>${esc(user.role==='admin'?'Owner':user.role)} · <a href="/signout-with-chatgpt?return_to=%2F">Sign out</a></small>`:'Secure account access';document.querySelector('#support').textContent=s.supportPhone?'Support: '+s.supportPhone:'';
 if(!user){app.innerHTML=`<section class="card"><div class="eyebrow">LOCAL CARE, TRUSTED SERVICE</div><h1>Help for your home.</h1><p>AC repair, plumbing, electrical and washing machine services.</p><a class="primary" target="_top" href="/signin-with-chatgpt?return_to=%2F">Sign in with ChatGPT</a><p class="muted">This first release uses a ChatGPT account to sign in. ${s.ready?'Request a visit after signing in.':'Customer bookings are not open yet.'}</p></section>`;return;}
 app.innerHTML=`<div class="intro"><div><div class="eyebrow">${esc(s.brand)}</div><h1>${user.role==='admin'?'Your service desk':user.role==='technician'?'Your assigned visits':'Your home, cared for.'}</h1><p>${s.ready?'Booking requests are open.':'Setup in progress · new bookings are closed.'}</p></div><button class="quiet" id="refresh">Refresh updates</button></div>`+(user.role==='admin'?owner():user.role==='customer'?customer():'')+`<section><h2>${user.role==='admin'?'Booking requests':'Your bookings'}</h2><p class="muted">Updates appear here. Use Refresh updates to check changes. Payments are recorded as cash after service; online payment and SMS are not enabled.</p>${state.bookings.length?state.bookings.map(job).join(''):'<div class="card">No bookings yet.</div>'}</section>`;
 document.querySelector('#refresh').onclick=()=>refresh().catch(showError);app.querySelectorAll('form').forEach(f=>f.addEventListener('submit',save));villageSearch();
}
function owner(){const s=state.settings;return `<details class="card" ${!s.ready?'open':''}><summary>Business setup and booking availability</summary><p>Enter your actual service details before opening bookings. The visit windows are 9am–1pm and 2pm–6pm; confirm each request with the customer before assigning.</p><form data-action="settings">${field('brand','Business name',s.brand)}<div class="fields">${field('base','Business location',s.base)}${field('pin','Business PIN',s.pin)}${field('supportPhone','Support mobile',s.supportPhone,'tel')}${field('hours','Service hours',s.hours)}</div>${area('areas','Service villages (one per line)',s.areas.join('\n'))}<div class="fields">${field('visitFee','Visit fee (₹)',s.visitFee,'number')}${field('travelFee','Travel fee (₹)',s.travelFee,'number')}</div>${area('terms','Visit, cancellation and declined-repair terms',s.terms)}${area('privacy','Privacy, contact and data retention notice',s.privacy)}${check('ready','Open booking requests',s.ready)}${submit('Save business details')}</form></details><details class="card"><summary>Technician accounts</summary><p>Use each technician’s ChatGPT sign-in email. Only the owner can grant or remove staff access.</p><form data-action="technician">${field('name','Technician name')}${field('email','Sign-in email','','email')}<label>Skills<select name="skills" multiple required>${services()}</select></label>${submit('Add technician')}</form>${state.technicians.map(t=>`<form data-action="staff-toggle" data-id="${esc(t.id)}"><p>${esc(t.name)} · ${esc(t.email)} · ${t.active?'Active':'Inactive'}</p>${submit(t.active?'Deactivate account':'Reactivate account')}</form>`).join('')}</details><p><a class="link" href="/api/export">Download business data</a> · Keep exports private. Automated backups and restore verification are still pending.</p>`;}
function customer(){const s=state.settings;return `${s.ready?`<details class="card" open><summary>Request a service visit</summary><p>Serving: ${esc(s.areas.join(', '))}. ${esc(s.hours)}. Coverage and timing are confirmed after your request.</p><form data-action="create"><label>Service<select name="service">${services()}</select></label><div class="fields">${field('name','Your name')}${field('phone','Mobile number','','tel')}</div><div class="place-field">${field('village','Village')}<div id="places" class="place-options" aria-label="Village suggestions"></div><small id="place-help">Type at least 3 letters for map suggestions. You can enter the village manually.</small></div><div class="fields">${field('pin','PIN code')}${field('date','Preferred date','','date')}</div><label>Visit window<select name="window"><option>09:00–13:00</option><option>14:00–18:00</option></select></label>${area('landmark','House address, landmark and directions')}${area('issue','What needs fixing?')}<p>Visit fee ${money(s.visitFee)} + travel ${money(s.travelFee)}. Repair costs require your approval after inspection.</p><details><summary>Service terms and privacy</summary><pre>${esc(s.terms)}\n\n${esc(s.privacy)}</pre></details>${check('consent','I accept these visit charges and service terms.')}<small>Your number is used for service contact; phone verification is not enabled in this release.</small>${submit('Request visit')}</form></details>`:'<div class="card">The owner is finishing service setup. Booking requests will open after setup.</div>'}`;}
function actionForm(b,action,label,fields=''){return `<form data-action="${action}" data-id="${esc(b.id)}">${fields}${submit(label)}</form>`;}
function job(b){const role=state.user.role,t=state.technicians.find(x=>x.id===b.technicianId);let actions='';
 if(role==='admin'&&['requested','assigned'].includes(b.status))actions=actionForm(b,'assign','Assign technician',`<label>Technician<select name="technicianId" required><option value="">Choose</option>${state.technicians.filter(x=>x.active&&x.skills.includes(b.service)).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>${check('coverageConfirmed','I confirmed village coverage and the visit time with the customer.')}`);
 if(role==='customer'){
 if(['requested','assigned'].includes(b.status))actions+=actionForm(b,'cancel','Cancel request');
 if(b.status==='awaiting_approval')actions+=actionForm(b,'approve','Approve repair')+actionForm(b,'decline','Decline repair');
 if(['completed','declined'].includes(b.status)&&b.paymentStatus==='unpaid')actions+=actionForm(b,'cash','Choose cash payment');
 }
 if(role==='technician'){
 if(b.status==='assigned')actions=actionForm(b,'depart','Start journey',field('eta','Arrival estimate (minutes)',30,'number'));
 if(b.status==='en_route')actions=actionForm(b,'arrive','Mark arrived');
 if(b.status==='inspecting')actions=actionForm(b,'estimate','Send estimate',area('description','Proposed repair')+field('labor','Labour (₹)',0,'number')+field('parts','Parts (₹)',0,'number'));
 if(b.status==='approved')actions=actionForm(b,'start','Start approved repair');
 if(b.status==='repairing')actions=actionForm(b,'complete','Complete visit',area('notes','Completion notes')+check('checked','Work checked with the customer'));
 if(b.paymentStatus==='cash_pending')actions+=actionForm(b,'cash_received','Confirm cash received',check('received',`I received ${money(b.amountDue)} in cash.`));
 }
 return `<article class="card job"><span class="pill">${esc(b.status.replaceAll('_',' '))}</span><small>${esc(b.id)}</small><h3>${esc(state.services.find(s=>s.id===b.service)?.name)}</h3><p>${esc(b.name)} · ${esc(b.phone)}<br>${esc(b.village)} ${esc(b.pin)} · ${esc(b.landmark)}<br>${esc(b.date)} · ${esc(b.window)}${t?'<br>Technician: '+esc(t.name):''}${b.eta?'<br>Estimated arrival: '+b.eta+' minutes':''}</p><p>${esc(b.issue)}</p>${b.estimate?`<div class="receipt">${esc(b.estimate.description)}<br>Labour ${money(b.estimate.labor)} · parts ${money(b.estimate.parts)} · visit ${money(b.fees.visit)} · travel ${money(b.fees.travel)}<br><strong>Total ${money(b.estimate.total)}</strong></div>`:''}${b.amountDue!==undefined?`<p>Amount due ${money(b.amountDue)} · ${esc(b.paymentStatus.replaceAll('_',' '))}${b.receipt?' · Receipt '+esc(b.receipt):''}</p>`:''}${b.notes?`<p>${esc(b.notes)}</p>`:''}<div class="actions">${actions}</div></article>`;
}
function showError(e){notice.textContent=e.message;notice.scrollIntoView({block:'nearest'});}
async function save(event){event.preventDefault();if(busy)return;const f=event.currentTarget,fd=new FormData(f);let action=f.dataset.action,input=Object.fromEntries(fd);
 for(const k of ['visitFee','travelFee','eta','labor','parts'])if(k in input)input[k]=Number(input[k]);
 for(const k of ['ready','consent','coverageConfirmed','checked','received'])input[k]=fd.has(k);
 if(action==='settings'){input.version=state.settingsVersion;input.areas=input.areas.split('\n').map(s=>s.trim()).filter(Boolean);}
 if(action==='technician')input.skills=fd.getAll('skills');
 if(action==='staff-toggle'){const t=state.technicians.find(t=>t.id===f.dataset.id);action='technician';input={...t,active:!t.active};}
 if(action==='create')input.settingsVersion=state.settingsVersion;
 if(f.dataset.id&&action!=='technician'){input.id=f.dataset.id;input.version=state.bookings.find(b=>b.id===input.id).version;}
 const payload=JSON.stringify({action,input});if(f.retryPayload!==payload){f.retryPayload=payload;f.retryKey=crypto.randomUUID();}busy=true;f.querySelectorAll('button').forEach(b=>b.disabled=true);notice.textContent='Saving…';
 try{const r=await fetch('/api/actions',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':f.retryKey},body:payload});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save');notice.textContent='Saved.';await refresh();}catch(e){showError(e);}finally{busy=false;f.querySelectorAll('button').forEach(b=>b.disabled=false);}
}
function villageSearch(){const input=app.querySelector('[name=village]');if(!input)return;let timer,seq=0;const list=document.querySelector('#places'),help=document.querySelector('#place-help');input.addEventListener('input',()=>{clearTimeout(timer);const current=++seq;list.replaceChildren();if(input.value.trim().length<3)return;timer=setTimeout(async()=>{try{const r=await fetch('/api/places?q='+encodeURIComponent(input.value));const data=await r.json();if(current!==seq)return;if(!r.ok)throw Error(data.error);help.textContent='OpenStreetMap via Photon · Select a suggestion or enter your village manually.';for(const p of data.places){const b=document.createElement('button');b.type='button';b.textContent=p.label;b.onclick=()=>{input.value=p.name;app.querySelector('[name=pin]').value=p.postcode||'';list.replaceChildren();help.textContent=p.postcode?'Village and PIN selected.':'Village selected. Enter your PIN manually.';};list.append(b);}}catch(e){if(current===seq)help.textContent=e.message;}},500);});}
refresh().catch(showError);
