import {test} from 'node:test';
import assert from 'node:assert/strict';
import {apply,initialState} from '../backend/domain.mjs';
const customer={id:'c',role:'customer'},owner={id:'o',role:'admin'},tech={id:'tech-1',role:'technician'};
const input={service:'ac',name:'Demo Customer',phone:'9000000000',village:'Sample village',landmark:'School',issue:'Not cooling',pin:'531116',slot:'Tomorrow · 9 am – 1 pm',consent:true};
const call=(s,u,a,i)=>apply(s,u,a,i,crypto.randomUUID());
test('approval gate, scoped access, completion and payment retries',()=>{const s=initialState();const b=apply(s,customer,'create',input,'create-1');assert.equal(apply(s,customer,'create',input,'create-1').id,b.id);assert.equal(s.bookings.length,1);assert.throws(()=>apply(s,customer,'create',{...input,name:'Changed'},'create-1'),/different request/);const id=b.id;assert.throws(()=>call(s,{id:'stranger',role:'customer'},'cancel',{id}),/not found/);assert.throws(()=>call(s,tech,'arrive',{id}),/not found/);assert.throws(()=>call(s,customer,'assign',{id,technicianId:'tech-1'}),/Owner/);call(s,owner,'assign',{id,technicianId:'tech-1'});assert.throws(()=>call(s,tech,'start',{id}),/changed/);call(s,tech,'depart',{id,eta:30});call(s,tech,'arrive',{id});call(s,tech,'estimate',{id,labor:350,parts:200,description:'Replace failed component'});assert.throws(()=>call(s,tech,'start',{id}),/changed/);assert.throws(()=>call(s,owner,'approve',{id}),/Customer approval/);call(s,customer,'approve',{id});call(s,tech,'start',{id});call(s,tech,'complete',{id,notes:'Replaced and tested'});call(s,customer,'pay',{id,method:'demo_upi',outcome:'failed'});assert.equal(s.bookings[0].paymentStatus,'failed');const p=apply(s,customer,'pay',{id,method:'demo_upi'},'pay-1');assert.equal(p.amountDue,749);assert.equal(p.paymentStatus,'paid');assert.equal(apply(s,customer,'pay',{id,method:'demo_upi'},'pay-1').receipt,p.receipt);assert.throws(()=>call(s,customer,'pay',{id,method:'demo_upi'}),/Already paid/);});
test('declined estimate charges only agreed visit and travel; cash needs confirmation',()=>{const s=initialState();const {id}=call(s,customer,'create',input);call(s,owner,'assign',{id,technicianId:'tech-1'});call(s,tech,'depart',{id,eta:15});call(s,tech,'arrive',{id});call(s,tech,'estimate',{id,labor:500,parts:100,description:'Repair'});call(s,customer,'decline',{id});assert.equal(s.bookings[0].amountDue,199);call(s,customer,'pay',{id,method:'cash'});assert.equal(s.bookings[0].paymentStatus,'cash_pending');assert.throws(()=>call(s,customer,'cash_received',{id}),/Assigned technician/);call(s,tech,'cash_received',{id});assert.equal(s.bookings[0].paymentStatus,'paid');});
test('invalid fees, inappropriate technician, cancellation and fee snapshot',()=>{const s=initialState();assert.throws(()=>call(s,customer,'create',{...input,phone:'123'}),/mobile/);const {id}=call(s,customer,'create',input);assert.throws(()=>call(s,owner,'assign',{id,technicianId:'tech-2'}),/skills/);call(s,owner,'settings',{brand:'Gramin',areas:['Sample'],visitFee:300,travelFee:100,radius:20});assert.equal(s.bookings[0].fees.visit,149);call(s,customer,'cancel',{id});assert.equal(s.bookings[0].amountDue,0);assert.throws(()=>call(s,owner,'assign',{id,technicianId:'tech-1'}),/changed/);});
