import {readFileSync,writeFileSync} from 'node:fs';
const path='live/app.js';let code=readFileSync(path,'utf8');const begin=code.indexOf('function owner(){'),end=code.indexOf('function customer(){');
const replacement=`function skillFields(selected=[]){return '<fieldset><legend>Skills</legend>'+state.services.map(s=>check('skills',esc(s.name)+' · '+esc(s.te),selected.includes(s.id)).replace('name="skills"','name="skills" value="'+s.id+'"')).join('')+'</fieldset>';}
function staffForm(t){return '<form data-action="technician"'+(t?' data-id="'+esc(t.id)+'"':'')+'>'+field('name','Technician name',t?.name||'')+field('email','Sign-in email',t?.email||'','email')+skillFields(t?.skills||[])+check('active','Enable technician account',t?.active||false)+submit(t?'Save technician changes':'Add technician')+'</form>';}
function owner(){const s=state.settings;return \`<section class="card"><h2>Setup progress</h2><p>✓ Business details saved · \${state.technicians.length} technician records · \${state.bookings.length} bookings</p><p>Edit the details below and press Save. Sample wording still needs your review before customer use.</p><details><summary>Pending launch work</summary><p>Review service hours, fees, service terms and privacy notice. Verify real technician sign-in emails. Backups, recovery checks, phone OTP, online payments and SMS/WhatsApp are still pending.</p></details></section><details class="card" open><summary>Business setup and booking availability</summary><p>Visit windows: 9am–1pm and 2pm–6pm. Confirm each request before assignment.</p><form data-action="settings">\${field('brand','Business name',s.brand)}<div class="fields">\${field('base','Business location',s.base)}\${field('pin','Business PIN',s.pin)}\${field('supportPhone','Support mobile',s.supportPhone,'tel')}\${field('hours','Service hours',s.hours)}</div>\${area('areas','Service villages (one per line)',s.areas.join('\\n'))}<div class="fields">\${field('visitFee','Visit fee (₹)',s.visitFee,'number')}\${field('travelFee','Travel fee (₹)',s.travelFee,'number')}</div>\${area('terms','Visit, cancellation and declined-repair terms',s.terms)}\${area('privacy','Privacy, contact and data retention notice',s.privacy)}\${check('ready','Open booking requests',s.ready)}\${submit('Save business details')}</form></details><details class="card" open><summary>Technician accounts</summary><p>Edit any saved technician below. Changing an enabled account’s email transfers its technician access to that sign-in email. Use only a verified staff email.</p>\${state.technicians.map(t=>\`<details class="card"><summary>Edit \${esc(t.name)} · \${t.active?'Enabled':'Disabled'}</summary>\${staffForm(t)}</details>\`).join('')}<details class="card" open><summary>Add a technician</summary><button class="quiet" type="button" id="sample-technician">Fill sample technician</button><p class="muted">The sample uses an example address and stays disabled. Replace it with a real staff email before enabling access.</p>\${staffForm()}</details></details><p><a class="link" href="/api/export">Download business data</a> · Automated backups and restore verification are still pending.</p>\`;}
`;
if(begin<0||end<0)throw Error('Owner UI missing');code=code.slice(0,begin)+replacement+code.slice(end);
code=code.replace('villageSearch();','villageSearch();const sample=document.querySelector("#sample-technician");if(sample)sample.onclick=()=>{const f=sample.parentElement.querySelector("form");f.elements.name.value="Sample Ravi";f.elements.email.value="ravi.sample@example.invalid";f.querySelectorAll("[name=skills]").forEach(el=>el.checked=["ac","washing"].includes(el.value));f.elements.active.checked=false;notice.textContent="Sample filled. Edit it, then choose Add technician. The account is disabled.";};');
writeFileSync(path,code);
